services:
  - type: web
    name: tele-energy-backend
    env: node
    rootDir: backend
    buildCommand: |
      cd backend
      npm install
      cd ../frontend
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
