services:
  - type: web
    name: tele-energy
    env: node
    buildCommand: |
    npm install
    cd ../frontend && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health 